In [2]:
from numpy import *
arr=array([1,2,3])

In [3]:
arr

array([1, 2, 3])

In [4]:
arr2=[[1,2,3],[4,5,6]]

In [5]:
arr2

[[1, 2, 3], [4, 5, 6]]

In [7]:
a=matrix(arr2)

In [8]:
diagonal(a)

array([1, 5])

In [9]:
a.max()

6

In [22]:
import numpy as np
arr2=np.array([[1,2,3,4],[4,5,6,7]])
arr3=arr2.flatten()

In [23]:
arr3

array([1, 2, 3, 4, 4, 5, 6, 7])

In [25]:
arr3.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [6, 7]]])

In [36]:
mat=[]
r= int(input())
c=int(input())
for i in range(r):
    a=[]
    for j in range(c):
        a.append(int(input()))
    mat.append(a)
print(mat) 

rev=[]
for i in range(len(mat)-2,-1,-1,):
    rev.append(mat[::-1])
print(rev)

2
2
1
2
3
4
[[1, 2], [3, 4]]
[[[3, 4], [1, 2]]]


In [71]:
mat=[]
r = int(input())
c=int(input())
for i in range(r):
    a=[]
    for j in range(c):
        a.append(int(input()))
    mat.append(a)
result=0
n=len(mat)//2
for i in range(n):
    for j in range(n):
        max_= max(mat[i][j],mat[i][(2*n-1)-j],mat[(2*n-1)-i][j],mat[(2*n-1)-i][(2*n-1)-j])
        result+=max_
        
print(result)

2
2
1
2
3
4
4
